name: Build and Publish DockerImage

on:
  pull_request:
    branches:
      - main
    types: [closed]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/${{ github.event.repository.name }}
          tags: ${{ github.sha }}, latest
          registry: docker.io
          dockerfile: Dockerfile
          target: runner
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
