name: Build and Publish DockerImage

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & Push Docker Image
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/rspec
          tags: ${{ github.run_number }}, latest
          registry: docker.io
          dockerfile: Dockerfile
          target: spec
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Run Sed
        run: sed -i -e "s/.*/${IMAGE_TAG}/g" .rspec.version
        env:
          IMAGE_TAG: ${{ github.run_id }} 

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          commit-message: |
              update container image
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          branch: create-pull-request/release/${{ github.run_number }}
          base: main
